import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Hello PWA',
  description: 'Hello PWA: Generated by create next app',
  manifest: '/manifest.webmanifest',
  'apple-touch-icon': '/icon-192x192.png',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
